# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from queueflow.models.job_config import JobConfig
from typing import Optional, Set
from typing_extensions import Self

class CronSchedule(BaseModel):
    """
    A recurring enqueue schedule. Expressions are standard 5-field crontab (`minute hour day-of-month month day-of-week`), evaluated in **UTC**; a 6/7-field form with leading seconds is also accepted.
    """ # noqa: E501
    config: Optional[JobConfig] = None
    created_at: datetime
    cron_expr: StrictStr
    enabled: StrictBool
    id: StrictStr
    last_enqueued_at: Optional[datetime] = None
    name: StrictStr = Field(description="Unique per tenant.")
    next_run_at: datetime = Field(description="The next instant this schedule fires. Missed occurrences (server down) collapse into at most one catch-up firing.")
    payload: Optional[Dict[str, Any]] = None
    queue_name: Optional[StrictStr] = Field(default=None, description="Queue for the enqueued jobs (the engine default when absent).")
    task_name: StrictStr
    tenant_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["config", "created_at", "cron_expr", "enabled", "id", "last_enqueued_at", "name", "next_run_at", "payload", "queue_name", "task_name", "tenant_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CronSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if last_enqueued_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_enqueued_at is None and "last_enqueued_at" in self.model_fields_set:
            _dict['last_enqueued_at'] = None

        # set to None if queue_name (nullable) is None
        # and model_fields_set contains the field
        if self.queue_name is None and "queue_name" in self.model_fields_set:
            _dict['queue_name'] = None

        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenant_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CronSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": JobConfig.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "created_at": obj.get("created_at"),
            "cron_expr": obj.get("cron_expr"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "last_enqueued_at": obj.get("last_enqueued_at"),
            "name": obj.get("name"),
            "next_run_at": obj.get("next_run_at"),
            "payload": obj.get("payload"),
            "queue_name": obj.get("queue_name"),
            "task_name": obj.get("task_name"),
            "tenant_id": obj.get("tenant_id")
        })
        return _obj


