# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DeadLetter(BaseModel):
    """
    A dead-lettered job: a terminal failure recorded for inspection and replay. The original job row remains (subject to retention); this entry captures why it died and, once replayed, which fresh job took its place.
    """ # noqa: E501
    created_at: datetime
    error_message: Optional[StrictStr] = None
    id: StrictInt
    job_id: StrictStr
    queue_name: Optional[StrictStr] = None
    reason: StrictStr = Field(description="Why the job dead-lettered: `max_attempts_exceeded`, `non_retryable`, or `handler_not_found`.")
    replay_job_id: Optional[StrictStr] = Field(default=None, description="The fresh job created by the replay.")
    replayed_at: Optional[datetime] = Field(default=None, description="Set once this entry has been replayed; a dead letter replays at most once.")
    task_name: Optional[StrictStr] = None
    tenant_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "error_message", "id", "job_id", "queue_name", "reason", "replay_job_id", "replayed_at", "task_name", "tenant_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeadLetter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if queue_name (nullable) is None
        # and model_fields_set contains the field
        if self.queue_name is None and "queue_name" in self.model_fields_set:
            _dict['queue_name'] = None

        # set to None if replay_job_id (nullable) is None
        # and model_fields_set contains the field
        if self.replay_job_id is None and "replay_job_id" in self.model_fields_set:
            _dict['replay_job_id'] = None

        # set to None if replayed_at (nullable) is None
        # and model_fields_set contains the field
        if self.replayed_at is None and "replayed_at" in self.model_fields_set:
            _dict['replayed_at'] = None

        # set to None if task_name (nullable) is None
        # and model_fields_set contains the field
        if self.task_name is None and "task_name" in self.model_fields_set:
            _dict['task_name'] = None

        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenant_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeadLetter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "error_message": obj.get("error_message"),
            "id": obj.get("id"),
            "job_id": obj.get("job_id"),
            "queue_name": obj.get("queue_name"),
            "reason": obj.get("reason"),
            "replay_job_id": obj.get("replay_job_id"),
            "replayed_at": obj.get("replayed_at"),
            "task_name": obj.get("task_name"),
            "tenant_id": obj.get("tenant_id")
        })
        return _obj


