# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from queueflow.models.backoff_strategy import BackoffStrategy
from typing import Optional, Set
from typing_extensions import Self

class JobConfig(BaseModel):
    """
    Per-job execution configuration. All durations are in seconds.
    """ # noqa: E501
    jitter_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Optional jitter in `0.0..=1.0`. `0.1` => +/-10% randomization of each retry delay, which spreads out thundering-herd retries.")
    max_retries: Annotated[int, Field(strict=True, ge=0)]
    priority: StrictInt = Field(description="Higher is claimed first within a queue; ties break on `scheduled_at`, then `created_at`.")
    retry_backoff: Optional[BackoffStrategy] = None
    retry_delay_secs: Annotated[int, Field(strict=True, ge=0)]
    retry_max_delay_secs: Annotated[int, Field(strict=True, ge=0)]
    timeout_secs: Annotated[int, Field(strict=True, ge=0)]
    __properties: ClassVar[List[str]] = ["jitter_factor", "max_retries", "priority", "retry_backoff", "retry_delay_secs", "retry_max_delay_secs", "timeout_secs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if jitter_factor (nullable) is None
        # and model_fields_set contains the field
        if self.jitter_factor is None and "jitter_factor" in self.model_fields_set:
            _dict['jitter_factor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jitter_factor": obj.get("jitter_factor"),
            "max_retries": obj.get("max_retries"),
            "priority": obj.get("priority"),
            "retry_backoff": obj.get("retry_backoff"),
            "retry_delay_secs": obj.get("retry_delay_secs"),
            "retry_max_delay_secs": obj.get("retry_max_delay_secs"),
            "timeout_secs": obj.get("timeout_secs")
        })
        return _obj


