# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from queueflow.models.backoff_strategy import BackoffStrategy
from typing import Optional, Set
from typing_extensions import Self

class JobConfigRequest(BaseModel):
    """
    Optional per-job configuration overrides.
    """ # noqa: E501
    jitter_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Retry-delay jitter in `0.0..=1.0` (e.g. `0.1` = +/-10%).")
    max_retries: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    priority: Optional[StrictInt] = Field(default=None, description="Higher is claimed first within a queue (ties: oldest first).")
    queue: Optional[StrictStr] = Field(default=None, description="Override the destination queue.")
    retry_backoff: Optional[BackoffStrategy] = Field(default=None, description="How retry delays grow between attempts (default exponential).")
    retry_delay_secs: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Base retry delay, in seconds.")
    retry_max_delay_secs: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Upper bound on any computed retry delay, in seconds.")
    timeout: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Per-attempt timeout, in seconds.")
    __properties: ClassVar[List[str]] = ["jitter_factor", "max_retries", "priority", "queue", "retry_backoff", "retry_delay_secs", "retry_max_delay_secs", "timeout"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if jitter_factor (nullable) is None
        # and model_fields_set contains the field
        if self.jitter_factor is None and "jitter_factor" in self.model_fields_set:
            _dict['jitter_factor'] = None

        # set to None if max_retries (nullable) is None
        # and model_fields_set contains the field
        if self.max_retries is None and "max_retries" in self.model_fields_set:
            _dict['max_retries'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if queue (nullable) is None
        # and model_fields_set contains the field
        if self.queue is None and "queue" in self.model_fields_set:
            _dict['queue'] = None

        # set to None if retry_backoff (nullable) is None
        # and model_fields_set contains the field
        if self.retry_backoff is None and "retry_backoff" in self.model_fields_set:
            _dict['retry_backoff'] = None

        # set to None if retry_delay_secs (nullable) is None
        # and model_fields_set contains the field
        if self.retry_delay_secs is None and "retry_delay_secs" in self.model_fields_set:
            _dict['retry_delay_secs'] = None

        # set to None if retry_max_delay_secs (nullable) is None
        # and model_fields_set contains the field
        if self.retry_max_delay_secs is None and "retry_max_delay_secs" in self.model_fields_set:
            _dict['retry_max_delay_secs'] = None

        # set to None if timeout (nullable) is None
        # and model_fields_set contains the field
        if self.timeout is None and "timeout" in self.model_fields_set:
            _dict['timeout'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jitter_factor": obj.get("jitter_factor"),
            "max_retries": obj.get("max_retries"),
            "priority": obj.get("priority"),
            "queue": obj.get("queue"),
            "retry_backoff": obj.get("retry_backoff"),
            "retry_delay_secs": obj.get("retry_delay_secs"),
            "retry_max_delay_secs": obj.get("retry_max_delay_secs"),
            "timeout": obj.get("timeout")
        })
        return _obj


