# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from queueflow.models.dead_letter import DeadLetter
from typing import Optional, Set
from typing_extensions import Self

class ListDeadLettersResponse(BaseModel):
    """
    ListDeadLettersResponse
    """ # noqa: E501
    dead_letters: List[DeadLetter]
    has_more: StrictBool
    limit: StrictInt
    offset: StrictInt
    total: Optional[StrictInt] = Field(default=None, description="Exact total match count; only present when `include_total=true`.")
    __properties: ClassVar[List[str]] = ["dead_letters", "has_more", "limit", "offset", "total"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListDeadLettersResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dead_letters (list)
        _items = []
        if self.dead_letters:
            for _item_dead_letters in self.dead_letters:
                if _item_dead_letters:
                    _items.append(_item_dead_letters.to_dict())
            _dict['dead_letters'] = _items
        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['total'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListDeadLettersResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dead_letters": [DeadLetter.from_dict(_item) for _item in obj["dead_letters"]] if obj.get("dead_letters") is not None else None,
            "has_more": obj.get("has_more"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "total": obj.get("total")
        })
        return _obj


