# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OnFailure(str, Enum):
    """
    What to do with downstream steps when a step fails.
    """

    """
    allowed enum values
    """
    HALT = 'halt'
    SKIP = 'skip'
    CONTINUE = 'continue'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OnFailure from a JSON string"""
        return cls(json.loads(json_str))


