# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class StatsSnapshot(BaseModel):
    """
    Plain snapshot of [`EngineStats`].
    """ # noqa: E501
    jobs_completed: Annotated[int, Field(strict=True, ge=0)]
    jobs_created: Annotated[int, Field(strict=True, ge=0)]
    jobs_dead_lettered: Annotated[int, Field(strict=True, ge=0)]
    jobs_failed: Annotated[int, Field(strict=True, ge=0)]
    jobs_retried: Annotated[int, Field(strict=True, ge=0)]
    workflows_completed: Annotated[int, Field(strict=True, ge=0)]
    workflows_created: Annotated[int, Field(strict=True, ge=0)]
    workflows_failed: Annotated[int, Field(strict=True, ge=0)]
    __properties: ClassVar[List[str]] = ["jobs_completed", "jobs_created", "jobs_dead_lettered", "jobs_failed", "jobs_retried", "workflows_completed", "workflows_created", "workflows_failed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jobs_completed": obj.get("jobs_completed"),
            "jobs_created": obj.get("jobs_created"),
            "jobs_dead_lettered": obj.get("jobs_dead_lettered"),
            "jobs_failed": obj.get("jobs_failed"),
            "jobs_retried": obj.get("jobs_retried"),
            "workflows_completed": obj.get("workflows_completed"),
            "workflows_created": obj.get("workflows_created"),
            "workflows_failed": obj.get("workflows_failed")
        })
        return _obj


