# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StepStatus(str, Enum):
    """
    Lifecycle state of a single workflow step.
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    CANCELLED = 'cancelled'
    SKIPPED = 'skipped'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StepStatus from a JSON string"""
        return cls(json.loads(json_str))


