# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.list_jobs_response import ListJobsResponse

class TestListJobsResponse(unittest.TestCase):
    """ListJobsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListJobsResponse:
        """Test ListJobsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListJobsResponse`
        """
        model = ListJobsResponse()
        if include_optional:
            return ListJobsResponse(
                has_more = True,
                jobs = [
                    queueflow.models.job.Job(
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        config = queueflow.models.job_config.JobConfig(
                            jitter_factor = 1.337, 
                            max_retries = 0, 
                            priority = 56, 
                            retry_backoff = 'fixed', 
                            retry_delay_secs = 0, 
                            retry_max_delay_secs = 0, 
                            timeout_secs = 0, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        delivery_count = 0, 
                        error_message = '', 
                        id = '', 
                        idempotency_key = '', 
                        metadata = {
                            'key' : null
                            }, 
                        next_retry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        payload = {
                            'key' : null
                            }, 
                        queue_name = '', 
                        result = {
                            'key' : null
                            }, 
                        retry_count = 0, 
                        scheduled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'pending', 
                        task_name = '', 
                        tenant_id = '', 
                        workflow_id = '', 
                        workflow_step_id = '', )
                    ],
                limit = 56,
                next_cursor = '',
                offset = 56,
                total = 56
            )
        else:
            return ListJobsResponse(
                has_more = True,
                jobs = [
                    queueflow.models.job.Job(
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        config = queueflow.models.job_config.JobConfig(
                            jitter_factor = 1.337, 
                            max_retries = 0, 
                            priority = 56, 
                            retry_backoff = 'fixed', 
                            retry_delay_secs = 0, 
                            retry_max_delay_secs = 0, 
                            timeout_secs = 0, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        delivery_count = 0, 
                        error_message = '', 
                        id = '', 
                        idempotency_key = '', 
                        metadata = {
                            'key' : null
                            }, 
                        next_retry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        payload = {
                            'key' : null
                            }, 
                        queue_name = '', 
                        result = {
                            'key' : null
                            }, 
                        retry_count = 0, 
                        scheduled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'pending', 
                        task_name = '', 
                        tenant_id = '', 
                        workflow_id = '', 
                        workflow_step_id = '', )
                    ],
                limit = 56,
                offset = 56,
        )
        """

    def testListJobsResponse(self):
        """Test ListJobsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
