# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.create_batch_jobs_request import CreateBatchJobsRequest

class TestCreateBatchJobsRequest(unittest.TestCase):
    """CreateBatchJobsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBatchJobsRequest:
        """Test CreateBatchJobsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBatchJobsRequest`
        """
        model = CreateBatchJobsRequest()
        if include_optional:
            return CreateBatchJobsRequest(
                jobs = [
                    queueflow.models.create_job_request.CreateJobRequest(
                        config = queueflow.models.job_config_request.JobConfigRequest(
                            jitter_factor = 1.337, 
                            max_retries = 0, 
                            priority = 56, 
                            queue = '', 
                            retry_backoff = 'fixed', 
                            retry_delay_secs = 0, 
                            retry_max_delay_secs = 0, 
                            timeout = 0, ), 
                        payload = {
                            'key' : null
                            }, 
                        run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_name = '', )
                    ]
            )
        else:
            return CreateBatchJobsRequest(
                jobs = [
                    queueflow.models.create_job_request.CreateJobRequest(
                        config = queueflow.models.job_config_request.JobConfigRequest(
                            jitter_factor = 1.337, 
                            max_retries = 0, 
                            priority = 56, 
                            queue = '', 
                            retry_backoff = 'fixed', 
                            retry_delay_secs = 0, 
                            retry_max_delay_secs = 0, 
                            timeout = 0, ), 
                        payload = {
                            'key' : null
                            }, 
                        run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_name = '', )
                    ],
        )
        """

    def testCreateBatchJobsRequest(self):
        """Test CreateBatchJobsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
