# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.list_workflows_response import ListWorkflowsResponse

class TestListWorkflowsResponse(unittest.TestCase):
    """ListWorkflowsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkflowsResponse:
        """Test ListWorkflowsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkflowsResponse`
        """
        model = ListWorkflowsResponse()
        if include_optional:
            return ListWorkflowsResponse(
                has_more = True,
                limit = 56,
                next_cursor = '',
                offset = 56,
                total = 56,
                workflows = [
                    queueflow.models.workflow.Workflow(
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        context = {
                            'key' : null
                            }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        metadata = {
                            'key' : null
                            }, 
                        name = '', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'created', 
                        steps = [
                            queueflow.models.workflow_step.WorkflowStep(
                                config = queueflow.models.job_config.JobConfig(
                                    jitter_factor = 1.337, 
                                    max_retries = 0, 
                                    priority = 56, 
                                    retry_backoff = 'fixed', 
                                    retry_delay_secs = 0, 
                                    retry_max_delay_secs = 0, 
                                    timeout_secs = 0, ), 
                                depends_on = [
                                    ''
                                    ], 
                                name = '', 
                                on_failure = 'halt', 
                                on_success = 'continue', 
                                payload = {
                                    'key' : null
                                    }, 
                                task_name = '', )
                            ], 
                        tenant_id = '', )
                    ]
            )
        else:
            return ListWorkflowsResponse(
                has_more = True,
                limit = 56,
                offset = 56,
                workflows = [
                    queueflow.models.workflow.Workflow(
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        context = {
                            'key' : null
                            }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        metadata = {
                            'key' : null
                            }, 
                        name = '', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'created', 
                        steps = [
                            queueflow.models.workflow_step.WorkflowStep(
                                config = queueflow.models.job_config.JobConfig(
                                    jitter_factor = 1.337, 
                                    max_retries = 0, 
                                    priority = 56, 
                                    retry_backoff = 'fixed', 
                                    retry_delay_secs = 0, 
                                    retry_max_delay_secs = 0, 
                                    timeout_secs = 0, ), 
                                depends_on = [
                                    ''
                                    ], 
                                name = '', 
                                on_failure = 'halt', 
                                on_success = 'continue', 
                                payload = {
                                    'key' : null
                                    }, 
                                task_name = '', )
                            ], 
                        tenant_id = '', )
                    ],
        )
        """

    def testListWorkflowsResponse(self):
        """Test ListWorkflowsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
