# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.workflow_diagram_response import WorkflowDiagramResponse

class TestWorkflowDiagramResponse(unittest.TestCase):
    """WorkflowDiagramResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowDiagramResponse:
        """Test WorkflowDiagramResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowDiagramResponse`
        """
        model = WorkflowDiagramResponse()
        if include_optional:
            return WorkflowDiagramResponse(
                diagram = '',
                format = ''
            )
        else:
            return WorkflowDiagramResponse(
                diagram = '',
                format = '',
        )
        """

    def testWorkflowDiagramResponse(self):
        """Test WorkflowDiagramResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
