# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.api.worker_api import WorkerApi


class TestWorkerApi(unittest.TestCase):
    """WorkerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkerApi()

    def tearDown(self) -> None:
        pass

    def test_complete_job(self) -> None:
        """Test case for complete_job

        """
        pass

    def test_fail_job(self) -> None:
        """Test case for fail_job

        """
        pass

    def test_heartbeat_job(self) -> None:
        """Test case for heartbeat_job

        """
        pass

    def test_lease_jobs(self) -> None:
        """Test case for lease_jobs

        """
        pass


if __name__ == '__main__':
    unittest.main()
