# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.on_failure import OnFailure

class TestOnFailure(unittest.TestCase):
    """OnFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnFailure(self):
        """Test OnFailure"""
        # inst = OnFailure()

if __name__ == '__main__':
    unittest.main()
