# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.workflow_step import WorkflowStep

class TestWorkflowStep(unittest.TestCase):
    """WorkflowStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowStep:
        """Test WorkflowStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowStep`
        """
        model = WorkflowStep()
        if include_optional:
            return WorkflowStep(
                config = queueflow.models.job_config.JobConfig(
                    jitter_factor = 1.337, 
                    max_retries = 0, 
                    priority = 56, 
                    retry_backoff = 'fixed', 
                    retry_delay_secs = 0, 
                    retry_max_delay_secs = 0, 
                    timeout_secs = 0, ),
                depends_on = [
                    ''
                    ],
                metadata = {
                    'key' : null
                    },
                name = '',
                on_failure = 'halt',
                on_success = 'continue',
                payload = {
                    'key' : null
                    },
                task_name = ''
            )
        else:
            return WorkflowStep(
                name = '',
                task_name = '',
        )
        """

    def testWorkflowStep(self):
        """Test WorkflowStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
