# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.workflow_status import WorkflowStatus

class TestWorkflowStatus(unittest.TestCase):
    """WorkflowStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowStatus(self):
        """Test WorkflowStatus"""
        # inst = WorkflowStatus()

if __name__ == '__main__':
    unittest.main()
