# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.list_dead_letters_response import ListDeadLettersResponse

class TestListDeadLettersResponse(unittest.TestCase):
    """ListDeadLettersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListDeadLettersResponse:
        """Test ListDeadLettersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListDeadLettersResponse`
        """
        model = ListDeadLettersResponse()
        if include_optional:
            return ListDeadLettersResponse(
                dead_letters = [
                    queueflow.models.dead_letter.DeadLetter(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error_message = '', 
                        id = 56, 
                        job_id = '', 
                        queue_name = '', 
                        reason = '', 
                        replay_job_id = '', 
                        replayed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_name = '', 
                        tenant_id = '', )
                    ],
                has_more = True,
                limit = 56,
                next_cursor = '',
                offset = 56,
                total = 56
            )
        else:
            return ListDeadLettersResponse(
                dead_letters = [
                    queueflow.models.dead_letter.DeadLetter(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error_message = '', 
                        id = 56, 
                        job_id = '', 
                        queue_name = '', 
                        reason = '', 
                        replay_job_id = '', 
                        replayed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        task_name = '', 
                        tenant_id = '', )
                    ],
                has_more = True,
                limit = 56,
                offset = 56,
        )
        """

    def testListDeadLettersResponse(self):
        """Test ListDeadLettersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
