# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.complete_job_request import CompleteJobRequest

class TestCompleteJobRequest(unittest.TestCase):
    """CompleteJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompleteJobRequest:
        """Test CompleteJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompleteJobRequest`
        """
        model = CompleteJobRequest()
        if include_optional:
            return CompleteJobRequest(
                lease_token = '',
                result = {
                    'key' : null
                    }
            )
        else:
            return CompleteJobRequest(
                lease_token = '',
        )
        """

    def testCompleteJobRequest(self):
        """Test CompleteJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
