# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_job(self) -> None:
        """Test case for cancel_job

        """
        pass

    def test_create_batch_jobs(self) -> None:
        """Test case for create_batch_jobs

        """
        pass

    def test_create_job(self) -> None:
        """Test case for create_job

        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        """
        pass

    def test_list_jobs(self) -> None:
        """Test case for list_jobs

        """
        pass

    def test_stream_job_events(self) -> None:
        """Test case for stream_job_events

        Stream a job's status transitions as Server-Sent Events until it reaches a terminal state. Lets clients await completion without polling the REST endpoint themselves.
        """
        pass


if __name__ == '__main__':
    unittest.main()
