# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.create_cron_response import CreateCronResponse

class TestCreateCronResponse(unittest.TestCase):
    """CreateCronResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCronResponse:
        """Test CreateCronResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCronResponse`
        """
        model = CreateCronResponse()
        if include_optional:
            return CreateCronResponse(
                cron_id = ''
            )
        else:
            return CreateCronResponse(
                cron_id = '',
        )
        """

    def testCreateCronResponse(self):
        """Test CreateCronResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
