# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.create_job_response import CreateJobResponse

class TestCreateJobResponse(unittest.TestCase):
    """CreateJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJobResponse:
        """Test CreateJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateJobResponse`
        """
        model = CreateJobResponse()
        if include_optional:
            return CreateJobResponse(
                job_id = ''
            )
        else:
            return CreateJobResponse(
                job_id = '',
        )
        """

    def testCreateJobResponse(self):
        """Test CreateJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
