# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.api.dlq_api import DlqApi


class TestDlqApi(unittest.TestCase):
    """DlqApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DlqApi()

    def tearDown(self) -> None:
        pass

    def test_get_dead_letter(self) -> None:
        """Test case for get_dead_letter

        """
        pass

    def test_list_dead_letters(self) -> None:
        """Test case for list_dead_letters

        """
        pass

    def test_replay_dead_letter(self) -> None:
        """Test case for replay_dead_letter

        """
        pass


if __name__ == '__main__':
    unittest.main()
