# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.replay_dead_letter_response import ReplayDeadLetterResponse

class TestReplayDeadLetterResponse(unittest.TestCase):
    """ReplayDeadLetterResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplayDeadLetterResponse:
        """Test ReplayDeadLetterResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplayDeadLetterResponse`
        """
        model = ReplayDeadLetterResponse()
        if include_optional:
            return ReplayDeadLetterResponse(
                job_id = ''
            )
        else:
            return ReplayDeadLetterResponse(
                job_id = '',
        )
        """

    def testReplayDeadLetterResponse(self):
        """Test ReplayDeadLetterResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
