# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.fail_job_request import FailJobRequest

class TestFailJobRequest(unittest.TestCase):
    """FailJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FailJobRequest:
        """Test FailJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FailJobRequest`
        """
        model = FailJobRequest()
        if include_optional:
            return FailJobRequest(
                error = '',
                lease_token = '',
                retryable = True
            )
        else:
            return FailJobRequest(
                error = '',
                lease_token = '',
        )
        """

    def testFailJobRequest(self):
        """Test FailJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
