# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.create_job_request import CreateJobRequest

class TestCreateJobRequest(unittest.TestCase):
    """CreateJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJobRequest:
        """Test CreateJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateJobRequest`
        """
        model = CreateJobRequest()
        if include_optional:
            return CreateJobRequest(
                config = queueflow.models.job_config_request.JobConfigRequest(
                    jitter_factor = 1.337, 
                    max_retries = 0, 
                    priority = 56, 
                    queue = '', 
                    retry_backoff = 'fixed', 
                    retry_delay_secs = 0, 
                    retry_max_delay_secs = 0, 
                    timeout = 0, ),
                payload = {
                    'key' : null
                    },
                run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                task_name = ''
            )
        else:
            return CreateJobRequest(
                task_name = '',
        )
        """

    def testCreateJobRequest(self):
        """Test CreateJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
