# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.cron_schedule import CronSchedule

class TestCronSchedule(unittest.TestCase):
    """CronSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CronSchedule:
        """Test CronSchedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CronSchedule`
        """
        model = CronSchedule()
        if include_optional:
            return CronSchedule(
                config = queueflow.models.job_config.JobConfig(
                    jitter_factor = 1.337, 
                    max_retries = 0, 
                    priority = 56, 
                    retry_backoff = 'fixed', 
                    retry_delay_secs = 0, 
                    retry_max_delay_secs = 0, 
                    timeout_secs = 0, ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cron_expr = '',
                enabled = True,
                id = '',
                last_enqueued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                next_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payload = {
                    'key' : null
                    },
                queue_name = '',
                task_name = '',
                tenant_id = ''
            )
        else:
            return CronSchedule(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cron_expr = '',
                enabled = True,
                id = '',
                name = '',
                next_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                task_name = '',
        )
        """

    def testCronSchedule(self):
        """Test CronSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
