# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.stats_snapshot import StatsSnapshot

class TestStatsSnapshot(unittest.TestCase):
    """StatsSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsSnapshot:
        """Test StatsSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsSnapshot`
        """
        model = StatsSnapshot()
        if include_optional:
            return StatsSnapshot(
                jobs_completed = 0,
                jobs_created = 0,
                jobs_dead_lettered = 0,
                jobs_failed = 0,
                jobs_retried = 0,
                workflows_completed = 0,
                workflows_created = 0,
                workflows_failed = 0
            )
        else:
            return StatsSnapshot(
                jobs_completed = 0,
                jobs_created = 0,
                jobs_dead_lettered = 0,
                jobs_failed = 0,
                jobs_retried = 0,
                workflows_completed = 0,
                workflows_created = 0,
                workflows_failed = 0,
        )
        """

    def testStatsSnapshot(self):
        """Test StatsSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
