# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.job_config_request import JobConfigRequest

class TestJobConfigRequest(unittest.TestCase):
    """JobConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobConfigRequest:
        """Test JobConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobConfigRequest`
        """
        model = JobConfigRequest()
        if include_optional:
            return JobConfigRequest(
                max_retries = 0,
                priority = 56,
                queue = '',
                timeout = 0
            )
        else:
            return JobConfigRequest(
        )
        """

    def testJobConfigRequest(self):
        """Test JobConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
