# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.api.cron_api import CronApi


class TestCronApi(unittest.TestCase):
    """CronApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CronApi()

    def tearDown(self) -> None:
        pass

    def test_create_cron(self) -> None:
        """Test case for create_cron

        """
        pass

    def test_delete_cron(self) -> None:
        """Test case for delete_cron

        """
        pass

    def test_get_cron(self) -> None:
        """Test case for get_cron

        """
        pass

    def test_list_crons(self) -> None:
        """Test case for list_crons

        """
        pass

    def test_pause_cron(self) -> None:
        """Test case for pause_cron

        """
        pass

    def test_resume_cron(self) -> None:
        """Test case for resume_cron

        """
        pass


if __name__ == '__main__':
    unittest.main()
