# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.models.dead_letter import DeadLetter

class TestDeadLetter(unittest.TestCase):
    """DeadLetter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeadLetter:
        """Test DeadLetter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeadLetter`
        """
        model = DeadLetter()
        if include_optional:
            return DeadLetter(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error_message = '',
                id = 56,
                job_id = '',
                queue_name = '',
                reason = '',
                replay_job_id = '',
                replayed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                task_name = '',
                tenant_id = ''
            )
        else:
            return DeadLetter(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 56,
                job_id = '',
                reason = '',
        )
        """

    def testDeadLetter(self):
        """Test DeadLetter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
