# coding: utf-8

"""
    QueueFlow API

    REST API for QueueFlow, a PostgreSQL-native distributed job queue and workflow engine.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from queueflow.api.workflows_api import WorkflowsApi


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_workflow(self) -> None:
        """Test case for cancel_workflow

        """
        pass

    def test_create_workflow(self) -> None:
        """Test case for create_workflow

        """
        pass

    def test_get_workflow(self) -> None:
        """Test case for get_workflow

        """
        pass

    def test_get_workflow_diagram(self) -> None:
        """Test case for get_workflow_diagram

        """
        pass

    def test_get_workflow_step_states(self) -> None:
        """Test case for get_workflow_step_states

        """
        pass

    def test_list_workflows(self) -> None:
        """Test case for list_workflows

        """
        pass


if __name__ == '__main__':
    unittest.main()
